In [2]:
import numpy as np
from scipy.stats import norm

In [3]:
sample = [172, 174, 168, 169, 171, 173, 175, 170, 169, 172]
population_mean= 170
std = 3 
samp_mean = np.mean(sample)
n = len(sample)

In [4]:
z_score = (samp_mean - population_mean)/(std/np.sqrt(n))
z_score

np.float64(1.3703203194063098)

In [5]:
p_value = 2 * (1 - norm.cdf(abs(z_score)))
p_value

np.float64(0.17058693287143756)

In [56]:
alpha = 0.05  # significance level is either given in question or we take it as 0.05
if p_value<alpha:
    print("Reject null hypothesis")
else: 
    print("accept Null Hypothesis")

Reject null hypothesis

### T Test

In [13]:
import numpy as np
from scipy import stats

In [14]:
sample = [172, 174, 168, 169, 171, 173, 175, 170, 169, 172]
sample_mean = np.mean(sample)
sample_std = np.std(sample, ddof=1) # In T-test ddof is generally 1.
n = len(sample)
mean_population = 170

In [15]:
t_stats = (sample_mean-population_mean)/(sample_std/np.sqrt(n))
t_stats

np.float64(1.7782469350914734)

In [18]:
p_value = 2 * (1 - stats.t.cdf(abs(t_stats),df=n-1))
p_value

np.float64(0.10907771593031335)

In [19]:
alpha = 0.05
if p_value<alpha:
    print("Reject Null Hypothesis")
else:
    print("Accept Null Hypothesis")

Accept Null Hypothesis

### Two Sample T Test

In [22]:

import numpy as np
from scipy import stats

In [23]:
group_A = [85, 88, 90, 92, 87, 85, 89, 91, 86, 88]
group_B = [82, 84, 80, 83, 81, 79, 78, 85, 84, 83]

In [24]:
t_value, p_value = stats.ttest_ind(group_A,group_B,equal_var=False)

In [25]:
t_value

np.float64(5.829604009507161)

In [26]:
alpha = 0.05
if p_value < alpha:
    print("Reject the Null Hypothesis")
else:
    print("Accept the Null Hypothesis")

Reject the Null Hypothesis

In [27]:
p_value

np.float64(1.610475598965881e-05)

### Chi Square Test

Works on Categorical Data

In [31]:
import numpy as np
import seaborn as sns
from scipy.stats import chi2_contingency
import pandas as pd

In [32]:
df = sns.load_dataset("titanic")
df.sample(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
614,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
780,1,3,female,13.0,0,0,7.2292,C,Third,child,False,NaN,Cherbourg,yes,True

In [34]:
contingency_table = pd.crosstab(df['sex'],df['survived'])
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [35]:
chi2, p_value, dof, expected = chi2_contingency(contingency_table)

In [36]:
expected

array([[193.47474747, 120.52525253],
       [355.52525253, 221.47474747]])

In [38]:
alpha = 0.05
if p_value<alpha:
    print("Reject Null Hypothesis and there is a significance relation between Gender and survival")
else: 
    print("Accept Null Hypothesis and there is no significance relation between Gender and Survival")

Reject Null Hypothesis and there is a significance relation between Gender and survival

### One Way ANOVA

In [39]:
import numpy as np
import seaborn as sns
from scipy.stats import f_oneway

In [40]:
df = sns.load_dataset("titanic")

In [47]:
df.sample(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
221,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
116,0,3,male,70.5,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [50]:
df = df[['pclass','age']].dropna()

In [51]:
df["pclass"].unique()

array([3, 1, 2])

In [52]:
class_1 = df[df['pclass']==1]['age']
class_2 = df[df['pclass']==2]['age']
class_3 = df[df['pclass']==3]['age']

In [53]:

f_stats, p_value = f_oneway(class_1, class_2, class_3)

In [54]:
f_stats

np.float64(57.443484340676214)

In [55]:
alpha = 0.05
if p_value < alpha:
    print("Reject the Null Hypothesis and there is a sifnificance dfference between atleast one pclass")
else:
    print("Accept the Null Hypothesis and there is no difference")

Reject the Null Hypothesis and there is a sifnificance dfference between atleast one pclass